[server]
# If true, will show a warning when you run a Streamlit-enabled script that's not an app (i.e. a script without a main section).
showWarningOnDirectExecution = true

[logger]
level = "info"

[client]
toolbarMode = "auto"

[theme]
primaryColor = "#4680FA"
backgroundColor = "#F0F2F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#262730"
font = "sans serif"

[runner]
# Automatically rerun script when the file is modified on disk.
fastReruns = true

[global]
# Use the custom requirements file for Python 3.12
requirementsFile = "requirements-py312.txt" 